/*
Owl Contract Api

Testing IERC20ApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_IERC20ApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IERC20ApiService InterfacesIERC20Allowance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var address string

		resp, httpRes, err := apiClient.IERC20Api.InterfacesIERC20Allowance(context.Background(), networkId, address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IERC20ApiService InterfacesIERC20Approve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var address string

		resp, httpRes, err := apiClient.IERC20Api.InterfacesIERC20Approve(context.Background(), networkId, address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IERC20ApiService InterfacesIERC20BalanceOf", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var address string

		resp, httpRes, err := apiClient.IERC20Api.InterfacesIERC20BalanceOf(context.Background(), networkId, address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IERC20ApiService InterfacesIERC20TotalSupply", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var address string

		resp, httpRes, err := apiClient.IERC20Api.InterfacesIERC20TotalSupply(context.Background(), networkId, address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IERC20ApiService InterfacesIERC20Transfer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var address string

		resp, httpRes, err := apiClient.IERC20Api.InterfacesIERC20Transfer(context.Background(), networkId, address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IERC20ApiService InterfacesIERC20TransferFrom", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var address string

		resp, httpRes, err := apiClient.IERC20Api.InterfacesIERC20TransferFrom(context.Background(), networkId, address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
