/**
 * Owl Contract Api
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.DeployBeaconProxyRequestDeployParams;
import org.openapitools.client.model.DeployTokenURIBaseURIRequestContractParams;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DeployTokenURIBaseURIRequest {
  
  @SerializedName("deployParams")
  private DeployBeaconProxyRequestDeployParams deployParams = null;
  @SerializedName("contractParams")
  private DeployTokenURIBaseURIRequestContractParams contractParams = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public DeployBeaconProxyRequestDeployParams getDeployParams() {
    return deployParams;
  }
  public void setDeployParams(DeployBeaconProxyRequestDeployParams deployParams) {
    this.deployParams = deployParams;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public DeployTokenURIBaseURIRequestContractParams getContractParams() {
    return contractParams;
  }
  public void setContractParams(DeployTokenURIBaseURIRequestContractParams contractParams) {
    this.contractParams = contractParams;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeployTokenURIBaseURIRequest deployTokenURIBaseURIRequest = (DeployTokenURIBaseURIRequest) o;
    return (this.deployParams == null ? deployTokenURIBaseURIRequest.deployParams == null : this.deployParams.equals(deployTokenURIBaseURIRequest.deployParams)) &&
        (this.contractParams == null ? deployTokenURIBaseURIRequest.contractParams == null : this.contractParams.equals(deployTokenURIBaseURIRequest.contractParams));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.deployParams == null ? 0: this.deployParams.hashCode());
    result = 31 * result + (this.contractParams == null ? 0: this.contractParams.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeployTokenURIBaseURIRequest {\n");
    
    sb.append("  deployParams: ").append(deployParams).append("\n");
    sb.append("  contractParams: ").append(contractParams).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
