/**
 * Owl Contract Api
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InterfacesIERC1820GetManagerRequestContractParams {
  
  @SerializedName("0")
  private String _0 = null;
  @SerializedName("account")
  private String account = null;

  /**
   * An ethereum address
   **/
  @ApiModelProperty(value = "An ethereum address")
  public String get0() {
    return _0;
  }
  public void set0(String _0) {
    this._0 = _0;
  }

  /**
   * An ethereum address
   **/
  @ApiModelProperty(value = "An ethereum address")
  public String getAccount() {
    return account;
  }
  public void setAccount(String account) {
    this.account = account;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterfacesIERC1820GetManagerRequestContractParams interfacesIERC1820GetManagerRequestContractParams = (InterfacesIERC1820GetManagerRequestContractParams) o;
    return (this._0 == null ? interfacesIERC1820GetManagerRequestContractParams._0 == null : this._0.equals(interfacesIERC1820GetManagerRequestContractParams._0)) &&
        (this.account == null ? interfacesIERC1820GetManagerRequestContractParams.account == null : this.account.equals(interfacesIERC1820GetManagerRequestContractParams.account));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this._0 == null ? 0: this._0.hashCode());
    result = 31 * result + (this.account == null ? 0: this.account.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterfacesIERC1820GetManagerRequestContractParams {\n");
    
    sb.append("  _0: ").append(_0).append("\n");
    sb.append("  account: ").append(account).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
