/**
 * Owl Contract Api
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InterfacesIERC2981SetterSetDefaultRoyaltyRequest {
  
  @SerializedName("contractParams")
  private InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams contractParams = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams getContractParams() {
    return contractParams;
  }
  public void setContractParams(InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams contractParams) {
    this.contractParams = contractParams;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterfacesIERC2981SetterSetDefaultRoyaltyRequest interfacesIERC2981SetterSetDefaultRoyaltyRequest = (InterfacesIERC2981SetterSetDefaultRoyaltyRequest) o;
    return (this.contractParams == null ? interfacesIERC2981SetterSetDefaultRoyaltyRequest.contractParams == null : this.contractParams.equals(interfacesIERC2981SetterSetDefaultRoyaltyRequest.contractParams));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.contractParams == null ? 0: this.contractParams.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterfacesIERC2981SetterSetDefaultRoyaltyRequest {\n");
    
    sb.append("  contractParams: ").append(contractParams).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
