/*
 * Owl Contract Api
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InterfacesIERC20ApproveRequestContractParams
 */
public class InterfacesIERC20ApproveRequestContractParamsTest {
    private final InterfacesIERC20ApproveRequestContractParams model = new InterfacesIERC20ApproveRequestContractParams();

    /**
     * Model tests for InterfacesIERC20ApproveRequestContractParams
     */
    @Test
    public void testInterfacesIERC20ApproveRequestContractParams() {
        // TODO: test InterfacesIERC20ApproveRequestContractParams
    }

    /**
     * Test the property '_0'
     */
    @Test
    public void _0Test() {
        // TODO: test _0
    }

    /**
     * Test the property '_1'
     */
    @Test
    public void _1Test() {
        // TODO: test _1
    }

    /**
     * Test the property 'spender'
     */
    @Test
    public void spenderTest() {
        // TODO: test spender
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

}
