/*
 * Owl Contract Api
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.InterfacesIUpgradeableBeaconUpgradeToRequestContractParams;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InterfacesIUpgradeableBeaconUpgradeToRequest
 */
public class InterfacesIUpgradeableBeaconUpgradeToRequestTest {
    private final InterfacesIUpgradeableBeaconUpgradeToRequest model = new InterfacesIUpgradeableBeaconUpgradeToRequest();

    /**
     * Model tests for InterfacesIUpgradeableBeaconUpgradeToRequest
     */
    @Test
    public void testInterfacesIUpgradeableBeaconUpgradeToRequest() {
        // TODO: test InterfacesIUpgradeableBeaconUpgradeToRequest
    }

    /**
     * Test the property 'contractParams'
     */
    @Test
    public void contractParamsTest() {
        // TODO: test contractParams
    }

}
