/*
 * Owl Contract Api
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.InterfacesIERC165SupportsInterface200ResponseResult;
import org.openapitools.client.model.InterfacesIERC165SupportsInterfaceRequestContractParams;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InterfacesIERC165SupportsInterface200Response
 */
public class InterfacesIERC165SupportsInterface200ResponseTest {
    private final InterfacesIERC165SupportsInterface200Response model = new InterfacesIERC165SupportsInterface200Response();

    /**
     * Model tests for InterfacesIERC165SupportsInterface200Response
     */
    @Test
    public void testInterfacesIERC165SupportsInterface200Response() {
        // TODO: test InterfacesIERC165SupportsInterface200Response
    }

    /**
     * Test the property 'contractParams'
     */
    @Test
    public void contractParamsTest() {
        // TODO: test contractParams
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

}
