/*
 * Owl Contract Api
 *
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DeployUpgradeableBeaconRequestContractParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeployUpgradeableBeaconRequestContractParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeployUpgradeableBeaconRequestContractParams
        //private DeployUpgradeableBeaconRequestContractParams instance;

        public DeployUpgradeableBeaconRequestContractParamsTests()
        {
            // TODO uncomment below to create an instance of DeployUpgradeableBeaconRequestContractParams
            //instance = new DeployUpgradeableBeaconRequestContractParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeployUpgradeableBeaconRequestContractParams
        /// </summary>
        [Fact]
        public void DeployUpgradeableBeaconRequestContractParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeployUpgradeableBeaconRequestContractParams
            //Assert.IsType<DeployUpgradeableBeaconRequestContractParams>(instance);
        }


        /// <summary>
        /// Test the property '_0'
        /// </summary>
        [Fact]
        public void _0Test()
        {
            // TODO unit test for the property '_0'
        }
        /// <summary>
        /// Test the property '_1'
        /// </summary>
        [Fact]
        public void _1Test()
        {
            // TODO unit test for the property '_1'
        }
        /// <summary>
        /// Test the property 'Admin'
        /// </summary>
        [Fact]
        public void AdminTest()
        {
            // TODO unit test for the property 'Admin'
        }
        /// <summary>
        /// Test the property 'Implementation'
        /// </summary>
        [Fact]
        public void ImplementationTest()
        {
            // TODO unit test for the property 'Implementation'
        }

    }

}
