/*
 * Owl Contract Api
 *
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InterfacesIContractURISetContractURIRequestContractParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InterfacesIContractURISetContractURIRequestContractParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InterfacesIContractURISetContractURIRequestContractParams
        //private InterfacesIContractURISetContractURIRequestContractParams instance;

        public InterfacesIContractURISetContractURIRequestContractParamsTests()
        {
            // TODO uncomment below to create an instance of InterfacesIContractURISetContractURIRequestContractParams
            //instance = new InterfacesIContractURISetContractURIRequestContractParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InterfacesIContractURISetContractURIRequestContractParams
        /// </summary>
        [Fact]
        public void InterfacesIContractURISetContractURIRequestContractParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" InterfacesIContractURISetContractURIRequestContractParams
            //Assert.IsType<InterfacesIContractURISetContractURIRequestContractParams>(instance);
        }


        /// <summary>
        /// Test the property '_0'
        /// </summary>
        [Fact]
        public void _0Test()
        {
            // TODO unit test for the property '_0'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
