/*
 * Owl Contract Api
 *
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InterfacesIERC1820SetManagerRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InterfacesIERC1820SetManagerRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InterfacesIERC1820SetManagerRequest
        //private InterfacesIERC1820SetManagerRequest instance;

        public InterfacesIERC1820SetManagerRequestTests()
        {
            // TODO uncomment below to create an instance of InterfacesIERC1820SetManagerRequest
            //instance = new InterfacesIERC1820SetManagerRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InterfacesIERC1820SetManagerRequest
        /// </summary>
        [Fact]
        public void InterfacesIERC1820SetManagerRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" InterfacesIERC1820SetManagerRequest
            //Assert.IsType<InterfacesIERC1820SetManagerRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ContractParams'
        /// </summary>
        [Fact]
        public void ContractParamsTest()
        {
            // TODO unit test for the property 'ContractParams'
        }

    }

}
