/*
 * Owl Contract Api
 *
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WebhooksReadmeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhooksReadmeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhooksReadmeRequest
        //private WebhooksReadmeRequest instance;

        public WebhooksReadmeRequestTests()
        {
            // TODO uncomment below to create an instance of WebhooksReadmeRequest
            //instance = new WebhooksReadmeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhooksReadmeRequest
        /// </summary>
        [Fact]
        public void WebhooksReadmeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhooksReadmeRequest
            //Assert.IsType<WebhooksReadmeRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
