/*
 * Owl Contract Api
 *
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeployUpgradeableBeaconRequestContractParams {
    /// An ethereum address
    #[serde(rename = "0", skip_serializing_if = "Option::is_none")]
    pub param_0: Option<String>,
    /// An ethereum address
    #[serde(rename = "1", skip_serializing_if = "Option::is_none")]
    pub param_1: Option<String>,
    /// An ethereum address
    #[serde(rename = "_admin", skip_serializing_if = "Option::is_none")]
    pub _admin: Option<String>,
    /// An ethereum address
    #[serde(rename = "implementation_", skip_serializing_if = "Option::is_none")]
    pub implementation_: Option<String>,
}

impl DeployUpgradeableBeaconRequestContractParams {
    pub fn new() -> DeployUpgradeableBeaconRequestContractParams {
        DeployUpgradeableBeaconRequestContractParams {
            param_0: None,
            param_1: None,
            _admin: None,
            implementation_: None,
        }
    }
}


