/*
 * Owl Contract Api
 *
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InterfacesIerc1155SetApprovalForAllRequest {
    #[serde(rename = "contractParams")]
    pub contract_params: Box<crate::models::InterfacesIerc1155SetApprovalForAllRequestContractParams>,
}

impl InterfacesIerc1155SetApprovalForAllRequest {
    pub fn new(contract_params: crate::models::InterfacesIerc1155SetApprovalForAllRequestContractParams) -> InterfacesIerc1155SetApprovalForAllRequest {
        InterfacesIerc1155SetApprovalForAllRequest {
            contract_params: Box::new(contract_params),
        }
    }
}


