/*
 * Owl Contract Api
 *
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InterfacesIerc20AllowanceRequest {
    #[serde(rename = "contractParams")]
    pub contract_params: Box<crate::models::InterfacesIerc20AllowanceRequestContractParams>,
}

impl InterfacesIerc20AllowanceRequest {
    pub fn new(contract_params: crate::models::InterfacesIerc20AllowanceRequestContractParams) -> InterfacesIerc20AllowanceRequest {
        InterfacesIerc20AllowanceRequest {
            contract_params: Box::new(contract_params),
        }
    }
}


