/*
 * Owl Contract Api
 *
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InterfacesIerc1155SafeBatchTransferFromRequestContractParams {
    /// An ethereum address
    #[serde(rename = "0", skip_serializing_if = "Option::is_none")]
    pub param_0: Option<String>,
    /// An ethereum address
    #[serde(rename = "1", skip_serializing_if = "Option::is_none")]
    pub param_1: Option<String>,
    #[serde(rename = "2", skip_serializing_if = "Option::is_none")]
    pub param_2: Option<Vec<String>>,
    #[serde(rename = "3", skip_serializing_if = "Option::is_none")]
    pub param_3: Option<Vec<String>>,
    /// An arbitrary length byte array
    #[serde(rename = "4", skip_serializing_if = "Option::is_none")]
    pub param_4: Option<String>,
    /// An ethereum address
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// An ethereum address
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<String>>,
    #[serde(rename = "amounts", skip_serializing_if = "Option::is_none")]
    pub amounts: Option<Vec<String>>,
    /// An arbitrary length byte array
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
}

impl InterfacesIerc1155SafeBatchTransferFromRequestContractParams {
    pub fn new() -> InterfacesIerc1155SafeBatchTransferFromRequestContractParams {
        InterfacesIerc1155SafeBatchTransferFromRequestContractParams {
            param_0: None,
            param_1: None,
            param_2: None,
            param_3: None,
            param_4: None,
            from: None,
            to: None,
            ids: None,
            amounts: None,
            data: None,
        }
    }
}


