/*
 * Owl Contract Api
 * Specification for our API focused on contract interactions
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * InterfacesIERC721MintableAutoIdMintBatchRequestContractParams
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-16T18:48:04.561997+03:00[Europe/Istanbul]")
public class InterfacesIERC721MintableAutoIdMintBatchRequestContractParams {
  public static final String SERIALIZED_NAME_0 = "0";
  @SerializedName(SERIALIZED_NAME_0)
  private List<String> _0;

  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private List<String> to;

  public InterfacesIERC721MintableAutoIdMintBatchRequestContractParams() {
  }

  public InterfacesIERC721MintableAutoIdMintBatchRequestContractParams _0(List<String> _0) {
    
    this._0 = _0;
    return this;
  }

  public InterfacesIERC721MintableAutoIdMintBatchRequestContractParams add0Item(String _0Item) {
    if (this._0 == null) {
      this._0 = new ArrayList<>();
    }
    this._0.add(_0Item);
    return this;
  }

   /**
   * Get _0
   * @return _0
  **/
  @javax.annotation.Nullable
  public List<String> get0() {
    return _0;
  }


  public void set0(List<String> _0) {
    this._0 = _0;
  }


  public InterfacesIERC721MintableAutoIdMintBatchRequestContractParams to(List<String> to) {
    
    this.to = to;
    return this;
  }

  public InterfacesIERC721MintableAutoIdMintBatchRequestContractParams addToItem(String toItem) {
    if (this.to == null) {
      this.to = new ArrayList<>();
    }
    this.to.add(toItem);
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @javax.annotation.Nullable
  public List<String> getTo() {
    return to;
  }


  public void setTo(List<String> to) {
    this.to = to;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterfacesIERC721MintableAutoIdMintBatchRequestContractParams interfacesIERC721MintableAutoIdMintBatchRequestContractParams = (InterfacesIERC721MintableAutoIdMintBatchRequestContractParams) o;
    return Objects.equals(this._0, interfacesIERC721MintableAutoIdMintBatchRequestContractParams._0) &&
        Objects.equals(this.to, interfacesIERC721MintableAutoIdMintBatchRequestContractParams.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_0, to);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterfacesIERC721MintableAutoIdMintBatchRequestContractParams {\n");
    sb.append("    _0: ").append(toIndentedString(_0)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("0");
    openapiFields.add("to");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InterfacesIERC721MintableAutoIdMintBatchRequestContractParams
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InterfacesIERC721MintableAutoIdMintBatchRequestContractParams.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InterfacesIERC721MintableAutoIdMintBatchRequestContractParams is not found in the empty JSON string", InterfacesIERC721MintableAutoIdMintBatchRequestContractParams.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!InterfacesIERC721MintableAutoIdMintBatchRequestContractParams.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InterfacesIERC721MintableAutoIdMintBatchRequestContractParams` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("0") != null && !jsonObj.get("0").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `0` to be an array in the JSON string but got `%s`", jsonObj.get("0").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("to") != null && !jsonObj.get("to").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `to` to be an array in the JSON string but got `%s`", jsonObj.get("to").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InterfacesIERC721MintableAutoIdMintBatchRequestContractParams.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InterfacesIERC721MintableAutoIdMintBatchRequestContractParams' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InterfacesIERC721MintableAutoIdMintBatchRequestContractParams> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InterfacesIERC721MintableAutoIdMintBatchRequestContractParams.class));

       return (TypeAdapter<T>) new TypeAdapter<InterfacesIERC721MintableAutoIdMintBatchRequestContractParams>() {
           @Override
           public void write(JsonWriter out, InterfacesIERC721MintableAutoIdMintBatchRequestContractParams value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InterfacesIERC721MintableAutoIdMintBatchRequestContractParams read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InterfacesIERC721MintableAutoIdMintBatchRequestContractParams given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InterfacesIERC721MintableAutoIdMintBatchRequestContractParams
  * @throws IOException if the JSON string is invalid with respect to InterfacesIERC721MintableAutoIdMintBatchRequestContractParams
  */
  public static InterfacesIERC721MintableAutoIdMintBatchRequestContractParams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InterfacesIERC721MintableAutoIdMintBatchRequestContractParams.class);
  }

 /**
  * Convert an instance of InterfacesIERC721MintableAutoIdMintBatchRequestContractParams to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

