//
// InterfacesIERC2981SetterSetTokenRoyaltyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InterfacesIERC2981SetterSetTokenRoyaltyRequest: Codable, JSONEncodable, Hashable {

    public var contractParams: InterfacesIERC2981SetterSetTokenRoyaltyRequestContractParams

    public init(contractParams: InterfacesIERC2981SetterSetTokenRoyaltyRequestContractParams) {
        self.contractParams = contractParams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contractParams
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contractParams, forKey: .contractParams)
    }
}

