/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param _0 An ethereum address
 * @param _1 An solidity boolean
 * @param `operator` An ethereum address
 * @param approved An solidity boolean
 */


data class InterfacesIERC721SetApprovalForAllRequestContractParams (

    /* An ethereum address */
    @Json(name = "0")
    val _0: kotlin.String? = null,

    /* An solidity boolean */
    @Json(name = "1")
    val _1: kotlin.Boolean? = null,

    /* An ethereum address */
    @Json(name = "operator")
    val `operator`: kotlin.String? = null,

    /* An solidity boolean */
    @Json(name = "_approved")
    val approved: kotlin.Boolean? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

