/*
Owl Contract Api

Specification for our API focused on contract interactions

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InterfacesIERC721MintableAutoIdMint200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfacesIERC721MintableAutoIdMint200Response{}

// InterfacesIERC721MintableAutoIdMint200Response struct for InterfacesIERC721MintableAutoIdMint200Response
type InterfacesIERC721MintableAutoIdMint200Response struct {
	ContractParams InterfacesIERC721MintableAutoIdMintRequestContractParams `json:"contractParams"`
	TxHash string `json:"txHash"`
}

// NewInterfacesIERC721MintableAutoIdMint200Response instantiates a new InterfacesIERC721MintableAutoIdMint200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfacesIERC721MintableAutoIdMint200Response(contractParams InterfacesIERC721MintableAutoIdMintRequestContractParams, txHash string) *InterfacesIERC721MintableAutoIdMint200Response {
	this := InterfacesIERC721MintableAutoIdMint200Response{}
	this.ContractParams = contractParams
	this.TxHash = txHash
	return &this
}

// NewInterfacesIERC721MintableAutoIdMint200ResponseWithDefaults instantiates a new InterfacesIERC721MintableAutoIdMint200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfacesIERC721MintableAutoIdMint200ResponseWithDefaults() *InterfacesIERC721MintableAutoIdMint200Response {
	this := InterfacesIERC721MintableAutoIdMint200Response{}
	return &this
}

// GetContractParams returns the ContractParams field value
func (o *InterfacesIERC721MintableAutoIdMint200Response) GetContractParams() InterfacesIERC721MintableAutoIdMintRequestContractParams {
	if o == nil {
		var ret InterfacesIERC721MintableAutoIdMintRequestContractParams
		return ret
	}

	return o.ContractParams
}

// GetContractParamsOk returns a tuple with the ContractParams field value
// and a boolean to check if the value has been set.
func (o *InterfacesIERC721MintableAutoIdMint200Response) GetContractParamsOk() (*InterfacesIERC721MintableAutoIdMintRequestContractParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractParams, true
}

// SetContractParams sets field value
func (o *InterfacesIERC721MintableAutoIdMint200Response) SetContractParams(v InterfacesIERC721MintableAutoIdMintRequestContractParams) {
	o.ContractParams = v
}

// GetTxHash returns the TxHash field value
func (o *InterfacesIERC721MintableAutoIdMint200Response) GetTxHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value
// and a boolean to check if the value has been set.
func (o *InterfacesIERC721MintableAutoIdMint200Response) GetTxHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxHash, true
}

// SetTxHash sets field value
func (o *InterfacesIERC721MintableAutoIdMint200Response) SetTxHash(v string) {
	o.TxHash = v
}

func (o InterfacesIERC721MintableAutoIdMint200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfacesIERC721MintableAutoIdMint200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contractParams"] = o.ContractParams
	toSerialize["txHash"] = o.TxHash
	return toSerialize, nil
}

type NullableInterfacesIERC721MintableAutoIdMint200Response struct {
	value *InterfacesIERC721MintableAutoIdMint200Response
	isSet bool
}

func (v NullableInterfacesIERC721MintableAutoIdMint200Response) Get() *InterfacesIERC721MintableAutoIdMint200Response {
	return v.value
}

func (v *NullableInterfacesIERC721MintableAutoIdMint200Response) Set(val *InterfacesIERC721MintableAutoIdMint200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfacesIERC721MintableAutoIdMint200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfacesIERC721MintableAutoIdMint200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfacesIERC721MintableAutoIdMint200Response(val *InterfacesIERC721MintableAutoIdMint200Response) *NullableInterfacesIERC721MintableAutoIdMint200Response {
	return &NullableInterfacesIERC721MintableAutoIdMint200Response{value: val, isSet: true}
}

func (v NullableInterfacesIERC721MintableAutoIdMint200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfacesIERC721MintableAutoIdMint200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


