/*
Owl Contract Api

Specification for our API focused on contract interactions

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response{}

// InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response struct for InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response
type InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response struct {
	ContractParams map[string]interface{} `json:"contractParams"`
	Result InterfacesIERC1820InterfaceHash200ResponseResult `json:"result"`
}

// NewInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response instantiates a new InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response(contractParams map[string]interface{}, result InterfacesIERC1820InterfaceHash200ResponseResult) *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response {
	this := InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response{}
	this.ContractParams = contractParams
	this.Result = result
	return &this
}

// NewInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200ResponseWithDefaults instantiates a new InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200ResponseWithDefaults() *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response {
	this := InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response{}
	return &this
}

// GetContractParams returns the ContractParams field value
func (o *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) GetContractParams() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ContractParams
}

// GetContractParamsOk returns a tuple with the ContractParams field value
// and a boolean to check if the value has been set.
func (o *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) GetContractParamsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ContractParams, true
}

// SetContractParams sets field value
func (o *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) SetContractParams(v map[string]interface{}) {
	o.ContractParams = v
}

// GetResult returns the Result field value
func (o *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) GetResult() InterfacesIERC1820InterfaceHash200ResponseResult {
	if o == nil {
		var ret InterfacesIERC1820InterfaceHash200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) GetResultOk() (*InterfacesIERC1820InterfaceHash200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) SetResult(v InterfacesIERC1820InterfaceHash200ResponseResult) {
	o.Result = v
}

func (o InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contractParams"] = o.ContractParams
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response struct {
	value *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response
	isSet bool
}

func (v NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) Get() *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response {
	return v.value
}

func (v *NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) Set(val *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response(val *InterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) *NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response {
	return &NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response{value: val, isSet: true}
}

func (v NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfacesIChainlinkAnyApiClientDEFAULTADMINROLE200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


