/*
Owl Contract Api

Specification for our API focused on contract interactions

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams{}

// InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams struct for InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams
type InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams struct {
	// An arbitrary length byte array
	Var0 *string `json:"0,omitempty"`
	// An arbitrary length byte array
	Var1 *string `json:"1,omitempty"`
	// An arbitrary length byte array
	FulfillPrefixData *string `json:"fulfillPrefixData,omitempty"`
	// An arbitrary length byte array
	FulfillResponseData *string `json:"fulfillResponseData,omitempty"`
}

// NewInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams instantiates a new InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams() *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams {
	this := InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams{}
	return &this
}

// NewInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParamsWithDefaults instantiates a new InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParamsWithDefaults() *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams {
	this := InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams{}
	return &this
}

// GetVar0 returns the Var0 field value if set, zero value otherwise.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) GetVar0() string {
	if o == nil || IsNil(o.Var0) {
		var ret string
		return ret
	}
	return *o.Var0
}

// GetVar0Ok returns a tuple with the Var0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) GetVar0Ok() (*string, bool) {
	if o == nil || IsNil(o.Var0) {
		return nil, false
	}
	return o.Var0, true
}

// HasVar0 returns a boolean if a field has been set.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) HasVar0() bool {
	if o != nil && !IsNil(o.Var0) {
		return true
	}

	return false
}

// SetVar0 gets a reference to the given string and assigns it to the Var0 field.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) SetVar0(v string) {
	o.Var0 = &v
}

// GetVar1 returns the Var1 field value if set, zero value otherwise.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) GetVar1() string {
	if o == nil || IsNil(o.Var1) {
		var ret string
		return ret
	}
	return *o.Var1
}

// GetVar1Ok returns a tuple with the Var1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) GetVar1Ok() (*string, bool) {
	if o == nil || IsNil(o.Var1) {
		return nil, false
	}
	return o.Var1, true
}

// HasVar1 returns a boolean if a field has been set.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) HasVar1() bool {
	if o != nil && !IsNil(o.Var1) {
		return true
	}

	return false
}

// SetVar1 gets a reference to the given string and assigns it to the Var1 field.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) SetVar1(v string) {
	o.Var1 = &v
}

// GetFulfillPrefixData returns the FulfillPrefixData field value if set, zero value otherwise.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) GetFulfillPrefixData() string {
	if o == nil || IsNil(o.FulfillPrefixData) {
		var ret string
		return ret
	}
	return *o.FulfillPrefixData
}

// GetFulfillPrefixDataOk returns a tuple with the FulfillPrefixData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) GetFulfillPrefixDataOk() (*string, bool) {
	if o == nil || IsNil(o.FulfillPrefixData) {
		return nil, false
	}
	return o.FulfillPrefixData, true
}

// HasFulfillPrefixData returns a boolean if a field has been set.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) HasFulfillPrefixData() bool {
	if o != nil && !IsNil(o.FulfillPrefixData) {
		return true
	}

	return false
}

// SetFulfillPrefixData gets a reference to the given string and assigns it to the FulfillPrefixData field.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) SetFulfillPrefixData(v string) {
	o.FulfillPrefixData = &v
}

// GetFulfillResponseData returns the FulfillResponseData field value if set, zero value otherwise.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) GetFulfillResponseData() string {
	if o == nil || IsNil(o.FulfillResponseData) {
		var ret string
		return ret
	}
	return *o.FulfillResponseData
}

// GetFulfillResponseDataOk returns a tuple with the FulfillResponseData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) GetFulfillResponseDataOk() (*string, bool) {
	if o == nil || IsNil(o.FulfillResponseData) {
		return nil, false
	}
	return o.FulfillResponseData, true
}

// HasFulfillResponseData returns a boolean if a field has been set.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) HasFulfillResponseData() bool {
	if o != nil && !IsNil(o.FulfillResponseData) {
		return true
	}

	return false
}

// SetFulfillResponseData gets a reference to the given string and assigns it to the FulfillResponseData field.
func (o *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) SetFulfillResponseData(v string) {
	o.FulfillResponseData = &v
}

func (o InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Var0) {
		toSerialize["0"] = o.Var0
	}
	if !IsNil(o.Var1) {
		toSerialize["1"] = o.Var1
	}
	if !IsNil(o.FulfillPrefixData) {
		toSerialize["fulfillPrefixData"] = o.FulfillPrefixData
	}
	if !IsNil(o.FulfillResponseData) {
		toSerialize["fulfillResponseData"] = o.FulfillResponseData
	}
	return toSerialize, nil
}

type NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams struct {
	value *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams
	isSet bool
}

func (v NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) Get() *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams {
	return v.value
}

func (v *NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) Set(val *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams(val *InterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) *NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams {
	return &NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams{value: val, isSet: true}
}

func (v NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfacesIChainlinkAnyApiConsumerFulfillRequestContractParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


