/*
Owl Contract Api

Specification for our API focused on contract interactions

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InterfacesIERC721GetApprovedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfacesIERC721GetApprovedRequest{}

// InterfacesIERC721GetApprovedRequest struct for InterfacesIERC721GetApprovedRequest
type InterfacesIERC721GetApprovedRequest struct {
	ContractParams InterfacesIERC721GetApprovedRequestContractParams `json:"contractParams"`
}

// NewInterfacesIERC721GetApprovedRequest instantiates a new InterfacesIERC721GetApprovedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfacesIERC721GetApprovedRequest(contractParams InterfacesIERC721GetApprovedRequestContractParams) *InterfacesIERC721GetApprovedRequest {
	this := InterfacesIERC721GetApprovedRequest{}
	this.ContractParams = contractParams
	return &this
}

// NewInterfacesIERC721GetApprovedRequestWithDefaults instantiates a new InterfacesIERC721GetApprovedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfacesIERC721GetApprovedRequestWithDefaults() *InterfacesIERC721GetApprovedRequest {
	this := InterfacesIERC721GetApprovedRequest{}
	return &this
}

// GetContractParams returns the ContractParams field value
func (o *InterfacesIERC721GetApprovedRequest) GetContractParams() InterfacesIERC721GetApprovedRequestContractParams {
	if o == nil {
		var ret InterfacesIERC721GetApprovedRequestContractParams
		return ret
	}

	return o.ContractParams
}

// GetContractParamsOk returns a tuple with the ContractParams field value
// and a boolean to check if the value has been set.
func (o *InterfacesIERC721GetApprovedRequest) GetContractParamsOk() (*InterfacesIERC721GetApprovedRequestContractParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractParams, true
}

// SetContractParams sets field value
func (o *InterfacesIERC721GetApprovedRequest) SetContractParams(v InterfacesIERC721GetApprovedRequestContractParams) {
	o.ContractParams = v
}

func (o InterfacesIERC721GetApprovedRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfacesIERC721GetApprovedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contractParams"] = o.ContractParams
	return toSerialize, nil
}

type NullableInterfacesIERC721GetApprovedRequest struct {
	value *InterfacesIERC721GetApprovedRequest
	isSet bool
}

func (v NullableInterfacesIERC721GetApprovedRequest) Get() *InterfacesIERC721GetApprovedRequest {
	return v.value
}

func (v *NullableInterfacesIERC721GetApprovedRequest) Set(val *InterfacesIERC721GetApprovedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfacesIERC721GetApprovedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfacesIERC721GetApprovedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfacesIERC721GetApprovedRequest(val *InterfacesIERC721GetApprovedRequest) *NullableInterfacesIERC721GetApprovedRequest {
	return &NullableInterfacesIERC721GetApprovedRequest{value: val, isSet: true}
}

func (v NullableInterfacesIERC721GetApprovedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfacesIERC721GetApprovedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


