/*
Owl Contract Api

Specification for our API focused on contract interactions

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InterfacesIERC2981SetterSetDefaultRoyalty200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfacesIERC2981SetterSetDefaultRoyalty200Response{}

// InterfacesIERC2981SetterSetDefaultRoyalty200Response struct for InterfacesIERC2981SetterSetDefaultRoyalty200Response
type InterfacesIERC2981SetterSetDefaultRoyalty200Response struct {
	ContractParams InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams `json:"contractParams"`
	TxHash string `json:"txHash"`
}

// NewInterfacesIERC2981SetterSetDefaultRoyalty200Response instantiates a new InterfacesIERC2981SetterSetDefaultRoyalty200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfacesIERC2981SetterSetDefaultRoyalty200Response(contractParams InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams, txHash string) *InterfacesIERC2981SetterSetDefaultRoyalty200Response {
	this := InterfacesIERC2981SetterSetDefaultRoyalty200Response{}
	this.ContractParams = contractParams
	this.TxHash = txHash
	return &this
}

// NewInterfacesIERC2981SetterSetDefaultRoyalty200ResponseWithDefaults instantiates a new InterfacesIERC2981SetterSetDefaultRoyalty200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfacesIERC2981SetterSetDefaultRoyalty200ResponseWithDefaults() *InterfacesIERC2981SetterSetDefaultRoyalty200Response {
	this := InterfacesIERC2981SetterSetDefaultRoyalty200Response{}
	return &this
}

// GetContractParams returns the ContractParams field value
func (o *InterfacesIERC2981SetterSetDefaultRoyalty200Response) GetContractParams() InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams {
	if o == nil {
		var ret InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams
		return ret
	}

	return o.ContractParams
}

// GetContractParamsOk returns a tuple with the ContractParams field value
// and a boolean to check if the value has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyalty200Response) GetContractParamsOk() (*InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractParams, true
}

// SetContractParams sets field value
func (o *InterfacesIERC2981SetterSetDefaultRoyalty200Response) SetContractParams(v InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) {
	o.ContractParams = v
}

// GetTxHash returns the TxHash field value
func (o *InterfacesIERC2981SetterSetDefaultRoyalty200Response) GetTxHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value
// and a boolean to check if the value has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyalty200Response) GetTxHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxHash, true
}

// SetTxHash sets field value
func (o *InterfacesIERC2981SetterSetDefaultRoyalty200Response) SetTxHash(v string) {
	o.TxHash = v
}

func (o InterfacesIERC2981SetterSetDefaultRoyalty200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfacesIERC2981SetterSetDefaultRoyalty200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contractParams"] = o.ContractParams
	toSerialize["txHash"] = o.TxHash
	return toSerialize, nil
}

type NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response struct {
	value *InterfacesIERC2981SetterSetDefaultRoyalty200Response
	isSet bool
}

func (v NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response) Get() *InterfacesIERC2981SetterSetDefaultRoyalty200Response {
	return v.value
}

func (v *NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response) Set(val *InterfacesIERC2981SetterSetDefaultRoyalty200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfacesIERC2981SetterSetDefaultRoyalty200Response(val *InterfacesIERC2981SetterSetDefaultRoyalty200Response) *NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response {
	return &NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response{value: val, isSet: true}
}

func (v NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfacesIERC2981SetterSetDefaultRoyalty200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


