/*
Owl Contract Api

Specification for our API focused on contract interactions

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InterfacesIERC1155SafeTransferFromRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfacesIERC1155SafeTransferFromRequest{}

// InterfacesIERC1155SafeTransferFromRequest struct for InterfacesIERC1155SafeTransferFromRequest
type InterfacesIERC1155SafeTransferFromRequest struct {
	ContractParams InterfacesIERC1155SafeTransferFromRequestContractParams `json:"contractParams"`
}

// NewInterfacesIERC1155SafeTransferFromRequest instantiates a new InterfacesIERC1155SafeTransferFromRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfacesIERC1155SafeTransferFromRequest(contractParams InterfacesIERC1155SafeTransferFromRequestContractParams) *InterfacesIERC1155SafeTransferFromRequest {
	this := InterfacesIERC1155SafeTransferFromRequest{}
	this.ContractParams = contractParams
	return &this
}

// NewInterfacesIERC1155SafeTransferFromRequestWithDefaults instantiates a new InterfacesIERC1155SafeTransferFromRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfacesIERC1155SafeTransferFromRequestWithDefaults() *InterfacesIERC1155SafeTransferFromRequest {
	this := InterfacesIERC1155SafeTransferFromRequest{}
	return &this
}

// GetContractParams returns the ContractParams field value
func (o *InterfacesIERC1155SafeTransferFromRequest) GetContractParams() InterfacesIERC1155SafeTransferFromRequestContractParams {
	if o == nil {
		var ret InterfacesIERC1155SafeTransferFromRequestContractParams
		return ret
	}

	return o.ContractParams
}

// GetContractParamsOk returns a tuple with the ContractParams field value
// and a boolean to check if the value has been set.
func (o *InterfacesIERC1155SafeTransferFromRequest) GetContractParamsOk() (*InterfacesIERC1155SafeTransferFromRequestContractParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractParams, true
}

// SetContractParams sets field value
func (o *InterfacesIERC1155SafeTransferFromRequest) SetContractParams(v InterfacesIERC1155SafeTransferFromRequestContractParams) {
	o.ContractParams = v
}

func (o InterfacesIERC1155SafeTransferFromRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfacesIERC1155SafeTransferFromRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contractParams"] = o.ContractParams
	return toSerialize, nil
}

type NullableInterfacesIERC1155SafeTransferFromRequest struct {
	value *InterfacesIERC1155SafeTransferFromRequest
	isSet bool
}

func (v NullableInterfacesIERC1155SafeTransferFromRequest) Get() *InterfacesIERC1155SafeTransferFromRequest {
	return v.value
}

func (v *NullableInterfacesIERC1155SafeTransferFromRequest) Set(val *InterfacesIERC1155SafeTransferFromRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfacesIERC1155SafeTransferFromRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfacesIERC1155SafeTransferFromRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfacesIERC1155SafeTransferFromRequest(val *InterfacesIERC1155SafeTransferFromRequest) *NullableInterfacesIERC1155SafeTransferFromRequest {
	return &NullableInterfacesIERC1155SafeTransferFromRequest{value: val, isSet: true}
}

func (v NullableInterfacesIERC1155SafeTransferFromRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfacesIERC1155SafeTransferFromRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


