/*
Owl Contract Api

Specification for our API focused on contract interactions

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams{}

// InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams struct for InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams
type InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams struct {
	// An ethereum address
	Var0 *string `json:"0,omitempty"`
	// A solidity uint96
	Var1 *string `json:"1,omitempty"`
	// An ethereum address
	Receiver *string `json:"receiver,omitempty"`
	// A solidity uint96
	FeeNumerator *string `json:"feeNumerator,omitempty"`
}

// NewInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams instantiates a new InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams() *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams {
	this := InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams{}
	return &this
}

// NewInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParamsWithDefaults instantiates a new InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParamsWithDefaults() *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams {
	this := InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams{}
	return &this
}

// GetVar0 returns the Var0 field value if set, zero value otherwise.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) GetVar0() string {
	if o == nil || IsNil(o.Var0) {
		var ret string
		return ret
	}
	return *o.Var0
}

// GetVar0Ok returns a tuple with the Var0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) GetVar0Ok() (*string, bool) {
	if o == nil || IsNil(o.Var0) {
		return nil, false
	}
	return o.Var0, true
}

// HasVar0 returns a boolean if a field has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) HasVar0() bool {
	if o != nil && !IsNil(o.Var0) {
		return true
	}

	return false
}

// SetVar0 gets a reference to the given string and assigns it to the Var0 field.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) SetVar0(v string) {
	o.Var0 = &v
}

// GetVar1 returns the Var1 field value if set, zero value otherwise.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) GetVar1() string {
	if o == nil || IsNil(o.Var1) {
		var ret string
		return ret
	}
	return *o.Var1
}

// GetVar1Ok returns a tuple with the Var1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) GetVar1Ok() (*string, bool) {
	if o == nil || IsNil(o.Var1) {
		return nil, false
	}
	return o.Var1, true
}

// HasVar1 returns a boolean if a field has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) HasVar1() bool {
	if o != nil && !IsNil(o.Var1) {
		return true
	}

	return false
}

// SetVar1 gets a reference to the given string and assigns it to the Var1 field.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) SetVar1(v string) {
	o.Var1 = &v
}

// GetReceiver returns the Receiver field value if set, zero value otherwise.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) GetReceiver() string {
	if o == nil || IsNil(o.Receiver) {
		var ret string
		return ret
	}
	return *o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) GetReceiverOk() (*string, bool) {
	if o == nil || IsNil(o.Receiver) {
		return nil, false
	}
	return o.Receiver, true
}

// HasReceiver returns a boolean if a field has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) HasReceiver() bool {
	if o != nil && !IsNil(o.Receiver) {
		return true
	}

	return false
}

// SetReceiver gets a reference to the given string and assigns it to the Receiver field.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) SetReceiver(v string) {
	o.Receiver = &v
}

// GetFeeNumerator returns the FeeNumerator field value if set, zero value otherwise.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) GetFeeNumerator() string {
	if o == nil || IsNil(o.FeeNumerator) {
		var ret string
		return ret
	}
	return *o.FeeNumerator
}

// GetFeeNumeratorOk returns a tuple with the FeeNumerator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) GetFeeNumeratorOk() (*string, bool) {
	if o == nil || IsNil(o.FeeNumerator) {
		return nil, false
	}
	return o.FeeNumerator, true
}

// HasFeeNumerator returns a boolean if a field has been set.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) HasFeeNumerator() bool {
	if o != nil && !IsNil(o.FeeNumerator) {
		return true
	}

	return false
}

// SetFeeNumerator gets a reference to the given string and assigns it to the FeeNumerator field.
func (o *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) SetFeeNumerator(v string) {
	o.FeeNumerator = &v
}

func (o InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Var0) {
		toSerialize["0"] = o.Var0
	}
	if !IsNil(o.Var1) {
		toSerialize["1"] = o.Var1
	}
	if !IsNil(o.Receiver) {
		toSerialize["receiver"] = o.Receiver
	}
	if !IsNil(o.FeeNumerator) {
		toSerialize["feeNumerator"] = o.FeeNumerator
	}
	return toSerialize, nil
}

type NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams struct {
	value *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams
	isSet bool
}

func (v NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) Get() *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams {
	return v.value
}

func (v *NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) Set(val *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams(val *InterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) *NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams {
	return &NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams{value: val, isSet: true}
}

func (v NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfacesIERC2981SetterSetDefaultRoyaltyRequestContractParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


